apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
    - application.giantswarm.io
  resources:
    - apps
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.giantswarm.io
  resources:
    - charts/status
  verbs:
    - create
    - patch
    - update
- apiGroups:
  - core.giantswarm.io
  resources:
  - charts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.giantswarm.io
  resources:
  - charts/status
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterrolebindings
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  verbs:
  - "bind"
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  verbs:
  - "create"
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - 'create'
- nonResourceURLs:
  - "/"
  - "/healthz"
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
