# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true



required = [
  "github.com/Azure/go-autorest/autorest",
  "github.com/docker/distribution/reference",
  "k8s.io/api/core/v1",
  "k8s.io/apimachinery/pkg/apis/meta/v1",
  "k8s.io/apiserver/pkg/endpoints/request"
]


[[override]]
  name = "github.com/giantswarm/helmclient"
  branch = "e2e_error_fix"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "9.1.0"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/apiextensions"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/appcatalog"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/e2e-harness"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/e2esetup"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/helmclient"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/k8sclient"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/kubeconfig"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/microerror"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/microkit"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/micrologger"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/operatorkit"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.15.4"

[[override]]
  branch = "master"
  name = "github.com/ghodss/yaml"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"


[prune]
  go-tests = true
  unused-packages = true
