# Default values for app-operator-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: app-operator
namespace: giantswarm
port: 8000
protocol: "TCP"

userID: 1000
groupID: 1000

replicas: 1

image:
  repository: giantswarm/app-operator
  tag: [[ .Version ]]

Installation:
  V1:
    Helm:
      HTTP:
        ClientTimeout: "5s"
    Kubernetes:
      API:
        Address: ""
    Registry:
      Domain: quay.io
    Secret:
      AppOperator:
        WebhookAuthToken: ""

operatorkit:
  resyncPeriod: "5m"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

deployment:
  requests:
    cpu: 250m
    memory: 250Mi
  limits:
    memory: 280Mi

verticalPodAutoscaler:
  enabled: true
