# Default values for app-operator-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: app-operator
namespace: giantswarm
port: 8000
protocol: "TCP"

app:
  watchNamespace: "org-ross"
  workloadClusterID: "av3a9"

helm:
  http:
    clientTimeout: "5s"

provider:
  kind: ""

userID: 1000
groupID: 1000

replicas: 1

registry:
  domain: docker.io

image:
  repository: giantswarm/app-operator
  tag: [[ .Version ]]

operatorkit:
  resyncPeriod: "5m"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

deployment:
  management:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      memory: 280Mi
  workload:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      memory: 50Mi

verticalPodAutoscaler:
  enabled: true
