# Default values for app-operator-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: app-operator
namespace: giantswarm
port: 8000
protocol: "TCP"

app:
  watchNamespace: ""
  workloadClusterID: ""
  dependencyWaitTimeoutMinutes: 30

helm:
  http:
    clientTimeout: "5s"

provider:
  kind: ""

kubernetes:
  disableClientCache: false

userID: 1000
groupID: 1000

replicas: 1

registry:
  domain: docker.io

image:
  repository: giantswarm/app-operator
  tag: "[[ .Version ]]"

operatorkit:
  resyncPeriod: "5m"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

deployment:
  management:
    requests:
      cpu: 150m
      memory: 200Mi
    limits:
      cpu: 250m
      memory: 250Mi
  workload:
    requests:
      cpu: 75m
      memory: 50Mi
    limits:
      cpu: 125m
      memory: 100Mi

verticalPodAutoscaler:
  enabled: true

# When this flag is true, app operator runs in special mode in order to be able to run in partially deployed clusters.
# Main differences are:
# - runs on master nodes
# - runs on hostNetwork
# - tolerates all taints
# - uses API hostname to reach the API to support kube-proxy being missing
# This mode is meant to be used during bootstrap of management clusters to be able to deploy basic system services
# (such as the CNI or the out-of-tree cloud controller managers) as a managed app.
# After the cluster is fully deployed, this flag should be switched to false.
bootstrapMode:
  apiServerPodPort: 443
  enabled: false

# Pod securityContext
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"

podSecurityStandards:
  enforced: false
