# Default values for app-operator-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: app-operator
namespace: giantswarm
port: 8000
protocol: "TCP"

userID: 1000
groupID: 1000

replicas: 1

image:
  repository: giantswarm/app-operator
  tag: [[ .Version ]]

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

deployment:
  requests:
    cpu: 250m
    memory: 250Mi

chart:
  webhook:
    authToken: ""
    baseURL: ""

helm:
  http:
    clientTimeout: "5s"

registry:
  domain: docker.io

operatorkit:
  resyncPeriod: "5m"
