apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:{{ .Values.port }}'
    service:
      app:
        unique: {{ include "resource.app.unique" . }}
      chart:
        webhookAuthToken: '{{ .Values.Installation.V1.Secret.AppOperator.WebhookAuthToken }}'
        {{- if hasSuffix "-unique" .Release.Name }}
        webhookBaseURL: 'http://{{ include "resource.default.name" . }}.{{ include "resource.default.namespace" . }}.svc.cluster.local:{{ .Values.port }}'
        {{- else }}
        webhookBaseURL: 'https://{{ include "resource.default.name" . }}.{{ .Values.Installation.V1.Kubernetes.API.Address }}'
        {{- end }}
      helm:
        http:
          clientTimeout: '{{ .Values.Installation.V1.Helm.HTTP.ClientTimeout }}'
      image:
        registry: '{{ .Values.Installation.V1.Registry.Domain }}' 
      kubernetes:
        incluster: true
