apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:{{ .Values.port }}'
    service:
      app:
        helmControllerBackend: {{  .Values.app.helmControllerBackend }}
        unique: {{ include "resource.app.unique" . }}
        watchNamespace: '{{ .Values.app.watchNamespace }}'
        workloadClusterID: '{{ .Values.app.workloadClusterID }}'
        dependencyWaitTimeoutMinutes: {{ .Values.app.dependencyWaitTimeoutMinutes }}
      helm:
        http:
          clientTimeout: '{{ .Values.helm.http.clientTimeout }}'
      image:
        registry: '{{ .Values.registry.domain }}'
      kubernetes:
        incluster: true
        disableClientCache: {{ $.Values.kubernetes.disableClientCache }}
      operatorkit:
        resyncPeriod: '{{ .Values.operatorkit.resyncPeriod }}'
      provider:
        kind: '{{ .Values.provider.kind }}'
