apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:{{ .Values.port }}'
    service:
      app:
        unique: {{ include "resource.app.unique" . }}
      collector:
        apps:
          defaultTeam: "batman"
          teams: |
            celestial: "azure-admission-controller,azure-collector,azure-operator,etcd-backup-operator,releases-azure"
            firecracker: "admission-controller,aws-operator,cluster-operator,kiam,releases-aws,route53-manager"
            ludacris: "bridge-operator,cert-exporter,cert-operator,coredns-app,flannel-operator,ignition-operator,kvm-operator,kube-state-metrics-app,metrics-server-app,net-exporter,node-operator,release-operator,releases-kvm"
            magic: "cluster-service,dex-app,g8s-cert-manager,g8s-efk,g8s-grafana,g8s-oauth2-proxy,g8s-prometheus,gatekeeper-app,gatekeeper-control-plane-rules,kubernetesd,rbac-operator,tokend,userd,vault-app"
      helm:
        http:
          clientTimeout: '{{ .Values.Installation.V1.Helm.HTTP.ClientTimeout }}'
      image:
        registry: '{{ .Values.Installation.V1.Registry.Domain }}' 
      kubernetes:
        incluster: true
