apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:{{ .Values.port }}'
    service:
      app:
        unique: {{ include "resource.app.unique" . }}
      chart:
        webhookAuthToken: '{{ .Values.chart.webhook.authToken }}'
        webhookBaseURL: 'https://{{ include "resource.default.name" . }}.{{ .Values.chart.webhook.baseURL }}'
      helm:
        http:
          clientTimeout: '{{ .Values.helm.http.clientTimeout }}'
      image:
        registry: '{{ .Values.registry.domain }}' 
      kubernetes:
        incluster: true
      operatorkit:
        resyncPeriod: '{{ .Values.operatorkit.resyncPeriod }}' 
