apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "labels.selector" . | nindent 8 }}
      annotations:
        app.giantswarm.io/config-checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
    spec:
      volumes:
      - name: {{ include "name" . }}-configmap
        configMap:
          name: {{ include "resource.default.name"  . }}
          items:
          - key: config.yaml
            path: config.yaml
      serviceAccountName: {{ include "resource.default.name"  . }}
      {{- if .Values.initialBootstrapMode }}
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: {{ include "name" . }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: {{ include "name" . }}-configmap
          mountPath: /var/run/{{ include "name" . }}/configmap/
        {{- if not .Values.initialBootstrapMode }}
        # When initialBootstrapMode is true, this pod runs in `hostNetwork` mode.
        # This means kubernetes automatically adds an hostPort field in the `ports` section below.
        # When initialBootstrapMode is set back to false, the hostPort field is not removed and that makes the replicaset to fail.
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        {{- end }}
        args:
        - daemon
        - --config.dirs=/var/run/{{ include "name" . }}/configmap/
        - --config.files=config
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.initialBootstrapMode }}
        - name: KUBERNETES_SERVICE_HOST
          value: 127.0.0.1
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
{{ include "resource.deployment.resources" . | indent 10 }}
