apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app-operator.selectorLabels" . | nindent 6 }}
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "app-operator.selectorLabels" . | nindent 8 }}
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      volumes:
      - name: {{ .Chart.Name }}
        configMap:
          name: {{ tpl .Values.resource.default.name  . }}
          items:
          - key: config.yaml
            path: config.yaml
      serviceAccountName: {{ tpl .Values.resource.default.name  . }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: {{ .Chart.Name }}
          mountPath: /var/run/{{ .Chart.Name }}/configmap/
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        args:
        - daemon
        - --config.dirs=/var/run/{{ .Chart.Name }}/configmap/
        - --config.files=config
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.deployment-resource | indent 10 }}
