{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ include "resource.default.name" . }}.{{ .Values.chart.webhook.baseURL }}
      secretName: {{ include "resource.default.name" . }}-ingress
  rules:
    - host: {{ include "resource.default.name" . }}.{{ .Values.chart.webhook.baseURL }}
      http:
        paths:
          - path: /status
            backend:
              serviceName: {{ include "resource.default.name" . }}
              servicePort: {{ .Values.port }}
