kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "app-operator.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: {{ .Values.port }}
      protocol: {{ .Values.protocol }}
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
