apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    name: {{ include "resource.default.name" . }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "resource.default.namespace" . }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  podMetricsEndpoints:
    - targetPort: {{ .Values.port }}
      relabelings:
        - replacement: {{ include "name" . }}
          targetLabel: app
        # The `service_priority` label value should always come from the Cluster CR label,
        # but in case of app-operators they always run in the Management clusters so which
        # are always the highest priority clusters, so it is ok for now to hard code it.
        - replacement: highest
          targetLabel: service_priority
