apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - "*"
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions/status
  verbs:
    - "*"
- apiGroups:
    - application.giantswarm.io
  resources:
    - apps
  verbs:
    - get
    - update
    - list
    - patch
    - watch
- apiGroups:
    - application.giantswarm.io
  resources:
    - apps/status
  verbs:
    - create
    - patch
    - update
- apiGroups:
    - application.giantswarm.io
  resources:
    - appcatalogs
  verbs:
    - get
    - list
    - patch
    - watch
- apiGroups:
    - application.giantswarm.io
  resources:
    - appcatalogs/status
  verbs:
    - create
    - patch
    - update
- apiGroups:
    - application.giantswarm.io
  resources:
    - appcatalogentries
  verbs:
    - "*"
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - create
    - delete
    - get
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
  verbs:
    - create
    - delete
    - get
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  verbs:
    - create
    - delete
    - get
    - use
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
  verbs:
    - create
    - delete
    - get
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
  verbs:
    - bind
    - create
    - delete
    - get
- apiGroups:
    - scheduling.k8s.io
  resources:
    - priorityclasses
  verbs:
    - get
    - delete
    - create
- apiGroups:
    - autoscaling.k8s.io
  resources:
    - verticalpodautoscalers
  verbs:
    - get
    - delete
    - create
- apiGroups:
    - ""
  resources:
    - services
    - serviceaccounts
  verbs:
    - get
    - delete
    - create
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - configmaps
    - secrets
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
- apiGroups:
    - ""
  resources:
    - pods/portforward
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
- nonResourceURLs:
  - "/"
  - "/healthz"
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.chart.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - application.giantswarm.io
    resources:
      - charts
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.chart.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.chart.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include  "resource.psp.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.psp.name" . }}
  apiGroup: rbac.authorization.k8s.io
