apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - "*"
- apiGroups:
    - application.giantswarm.io
  resources:
    - apps
  verbs:
    - get
    - list
    - patch
    - watch
- apiGroups:
    - application.giantswarm.io
  resources:
    - apps/status
  verbs:
    - create
    - patch
    - update
- apiGroups:
    - application.giantswarm.io
  resources:
    - appcatalogs
  verbs:
    - get
    - list
    - patch
    - watch
- apiGroups:
    - application.giantswarm.io
  resources:
    - appcatalogs/status
  verbs:
    - create
    - patch
    - update
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterrolebindings
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  verbs:
  - "bind"
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  verbs:
  - "create"
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - 'create'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - list
- apiGroups:
    - ""
  resources:
    - pods/portforward
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
- nonResourceURLs:
  - "/"
  - "/healthz"
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.chart.name  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - application.giantswarm.io
    resources:
      - charts
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace  . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.default.name  . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.chart.name  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace  . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.chart.name  . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.psp.name  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ tpl .Values.resource.psp.name  . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.psp.name  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace  . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.psp.name  . }}
  apiGroup: rbac.authorization.k8s.io
