apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "app-operator.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: {{ .Values.port }}
  selector:
    {{- include "app-operator.selectorLabels" . | nindent 4 }}
