{{ if eq (include "resource.vpa.enabled" .) "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ include "name" . }}
      controlledResources:
        - cpu
        - memory
      {{- if eq (include "resource.app.unique" .) "true" }}
      minAllowed:
        cpu: {{ .Values.deployment.management.requests.cpu }}
        memory: {{ .Values.deployment.management.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.deployment.management.limits.cpu }}
        memory: {{ .Values.deployment.management.limits.memory }}
      {{- else }}
      minAllowed:
        cpu: {{ .Values.deployment.workload.requests.cpu }}
        memory: {{ .Values.deployment.workload.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.deployment.workload.limits.cpu }}
        memory: {{ .Values.deployment.workload.limits.memory }}
      {{- end }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ include "resource.default.name"  . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
