{{ if eq (include "resource.vpa.enabled" .) "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ include "name" . }}
      controlledResources:
        - cpu
        - memory
      maxAllowed:
        cpu: 1000m
        memory: 1000Mi
      minAllowed:
        cpu: 250m
        memory: 250Mi
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ include "resource.default.name"  . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
