// Package annotation contains common Kubernetes metadata. These are defined in
// https://github.com/giantswarm/fmt/blob/master/kubernetes/annotations_and_labels.md.
package annotation

const (
	// Notes is for informational messages for resources generated by the operator.
	Notes = "giantswarm.io/notes"

	// AppOperatorPrefix the prefix for annotations that control logic inside app-operator.
	AppOperatorPrefix = "app-operator.giantswarm.io"

	// ChartOperatorPrefix is the prefix for annotations that control logic inside chart-operator.
	ChartOperatorPrefix = "chart-operator.giantswarm.io"

	// CordonReason is the name of the annotation that indicates
	// the reason of why operators should not apply any update to this app CR.
	CordonReason = "cordon-reason"

	// CordonUntil is the name of the annotation that indicates
	// the expiration date for this cordon rule.
	CordonUntil = "cordon-until"
)
